### PR TITLE
update requirements neccessary to run tests

### PR DESCRIPTION
**Pull request by ChainSafe**
the tests did not run until we installed pyblake2

### CODE REVIEW

**Comment by djrtwo** [comment]
Weird! What system/python version are you using?
The code tries to use the builtin `hashlib` before reverting to use `pyblake2`.
https://github.com/ethereum/beacon_chain/blob/b4179ec24e3530e17083c8ad22ae448cee51bd14/beacon_chain/utils/blake.py#L1-L4

**Comment by ChainSafe** [comment]
we're running Python 3.5.2
and Ubuntu 16.04

until we installed pyblake2 the tests did not run.
Thanks for the quick response.

**Comment by hwwhww** [comment]
According to [pyblack2](https://github.com/dchest/pyblake2): Python 3.6 and later have native support for BLAKE2 in hashlib derived from this implementation, with compatible API. This module should only be used if you want BLAKE2 in older Python versions, such as 2.7 or 3.5 and earlier.

Hmm, now the `evm` module in Py-EVM supports both 3.5 and 3.6, I think it's fine to add it, maybe add a comment like `for Python version older than Python 3.6`. Leave it until we provide different env setting in Py-EVM?

**Comment by djrtwo** [comment]
Yeah, I just saw that too. We can support 3.5 and 3.6 for now. I'll add the comment in the readme

**Pull request merged**
